# See docs:
#  https://pub.dev/packages/build_config
#  https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md
#  https://github.com/dart-lang/build/blob/master/docs/transforming_code.md

targets:
  $default:
    builders:
      objectbox_generator|resolver:
        enabled: true
        generate_for:
        - lib/app/data/model/model.dart

      objectbox_generator|generator:
        enabled: true

      json_serializable:
        generate_for:
        - lib/app/data/model/model.dart
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: false
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

builders:
  # Finds all classes annotated with @Entity annotation and creates intermediate files for the generator.
  # It's executed multiple times, once per file
  resolver:
    import: "package:objectbox_generator/objectbox_generator.dart"
    builder_factories: ["entityResolverFactory"]
    # build_extensions: Required. A map from input extension to the list of output extensions that may be created
    # for that input. This must match the merged buildExtensions maps from each Builder in builder_factories.
    build_extensions: {'.dart': ['.objectbox.info']}
    auto_apply: dependents
    build_to: cache

  # Writes objectbox_model.dart and objectbox-model.json from the prepared .objectbox.info files found in the repo.
  generator:
    import: "package:objectbox_generator/objectbox_generator.dart"
    builder_factories: ["codeGeneratorFactory"]
    # build_extensions: Required. A map from input extension to the list of output extensions that may be created
    # for that input. This must match the merged buildExtensions maps from each Builder in builder_factories.
    build_extensions:
      "$lib$": ["objectbox.g.dart"]
      "$test": ["objectbox.g.dart"]
    required_inputs: ['.objectbox.info']
    auto_apply: dependents
    build_to: source