name: monolith
version: 1.0.1
publish_to: none
description: Remote controll firmata.
environment:
  sdk: '>=2.19.0-254.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  dartx: ^1.1.0
  flutter_about_page: ^0.0.1
  flutter_easyloading: ^3.0.5
  get: ^4.6.5
  group_list_view: ^1.1.1
  grpc: ^3.0.2
  json_annotation: ^4.7.0
  nil: ^1.1.1
  protobuf: ^2.1.0
  reactive_forms: ^14.1.0
  # reactive_forms_annotations:
  # rounded_loading_button: ^2.0.8
  # isar:
  # hive: ^2.0.4
  # hive_flutter: ^1.1.0
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2
  package_info_plus: ^1.4.3+1
  reactive_advanced_switch: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lints: ^2.0.0
  # hive_generator: ^1.1.1
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  # reactive_forms_generator:
  objectbox_generator: ^1.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/
